name: "Vedant Singhania"

home:
  about:
    p1: "My name is Vedant Singhania and I am from Palo Alto, California. I have been coding since I was 12 and since then, I have become highly proficient in HTML, Python, Java, and JavaScript, and various frameworks, I have taken college-level computer science courses in high school, and I am now in the midst of my first year as a computer science major at San Jose State University. While I enjoy working on my own projects to help people in their everyday lives, I also have a passion for contributing to open source code in the community."
    p2: "Besides majoring in and having a deep passion for computer science, I am strong in my academics, I love singing in choir, and I often volunteer in the community."

projects:
  - name: "Tunestats"
    date: "Spring 2022"
    description: "An app powered by the Spotify API that shows your top songs, artists, and recently played songs."
    link: "https://tunestats.herokuapp.com"
  - name: "chairSense"
    date: "Fall 2021"
    description: "For wheelchair users, it can be hard to see what's behind the chair, especially when backing up or turning, which can be dangerous because there is a high potential to hit an object or person. The aim of this project is to solve that problem by creating a low-cost device that can detect obstacles and warn the wheelchair user so they don't hit objects or people."
    link: "https://github.com/raspberri05/chairsense"
    video: "https://www.youtube.com/embed/z72_hVvBnQc"
    paper: "assets/documents/chairSense_Research_Paper.pdf"
    papername: "View chairSense Research Paper"
  - name: "StockFalafel"
    date: "Summer 2020"
    description: "Many stock tracking and analysis services are often cluttered and hard to navigate and use, so we wanted to create something clean and simple. StockFalafel is an easy-to-use comprehensive stock-tracking app to help investors track stocks, with a customizable watchlist, detailed stock information, and the day’s most important stocks."
    link: "https://github.com/raspberri05/stockfalafel"
  - name: "ChatterBox"
    date: "Spring 2020"
    description: "A user-friendly chat app built for students featuring direct messaging, group messaging, and simple tools for group moderation.We wanted to make this app as approachable for students as possible, so we kept features simple and added some fun perks, like a random group name generator."
    link: "https://github.com/raspberri05/chatterbox"


  


