name: "Vedant Singhania"

home:
  about:
    p1: "My name is Vedant Singhania, from Palo Alto, California. I have been coding since I was 12, starting with MIT Scratch. Since then I have become proficient at 4 programming languages by self-teaching and taking computer science classes in school, which I have used to create applications to help people in their everyday lives. More recently, I have delved into the world of Arduino and C/C++ in order to create low-cost products to assist wheelchair users like me to be able to navigate the world more independently."
    p2: "Besides computer science, I am strong in academics and take Advanced Placement classes to challenge me, I love singing in choir, and I often volunteer at organizations locally and nationally."

projects:
  - name: "Wheelchair Obstacle Sensing System"
    date: "Fall 2021"
    description: "Description"
  - name: "StockFalafel"
    date: "Summer 2020"
    description: "Description"
  - name: "ChatterBox"
    date: "Spring 2020"
    description: "Description"


  


